name: Spell Check

on:
  workflow_dispatch:
  push:

jobs:
  cspell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: streetsidesoftware/cspell-action@v7
        with:
          config: .cspell/cspell.json
          incremental_files_only: false
          verbose: true
          files: |
                **/*.php
                **/*.class
                **/*.inc
                **/*.md
                **/*.txt
                **/*.html